CREATE TABLE remedio(
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	via VARCHAR(255) NOT NULL,
	lote VARCHAR(255) NOT NULL,
	quantidade INT NOT NULL,
	validade DATE NOT NULL,
	laboratorio VARCHAR(255) NOT NULL
);